### ISSUE TITLE
I encountered an issue during the simulation stage, please tell me how to display the calculated hash value.

### ISSUE THREAD

**Issue by qianyebai** [Zachamus/SHA256#1]
![H`4PLD~LS9@BV}MAO}EP 5W](https://github.com/Zachamus/SHA256/assets/170521885/f0c90b58-7d36-4c85-8da4-2a92cd045753)
  

And I would like to know where the final calculated hash value is stored.

**Comment by Zachamus** [comment]
Hi Qianyebai,

This SHA256 algo is not yet completed, I plan to finish it in the coming months. 
https://github.com/secworks/sha256
Here is a working version created by someone else.

Best,
Zach

**Comment by Zachamus** [comment]
Closing this thread, if you I hope I was helpful!
